# Generated by Django 4.1.3 on 2023-07-20 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_rename_user_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="price",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.AddField(
            model_name="purchase",
            name="priceId",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.price"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
