# Generated by Django 4.2.3 on 2023-07-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_purchase_price_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('image', models.URLField()),
                ('synopsis', models.CharField(max_length=500)),
                ('annee', models.IntegerField()),
                ('realisation', models.CharField(max_length=25)),
                ('flag', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='image',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AddField(
            model_name='session',
            name='filmId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.film'),
        ),
    ]
