# Generated by Django 4.2.3 on 2023-07-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_film_remove_session_image_remove_session_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('image', models.URLField()),
                ('synopsis', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('realisator', models.CharField(max_length=25)),
                ('flag', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='filmId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
